version: 2.1
commands:
  client_build:
    description: 'Build The UI Bits'
    steps:
      - run: yarn install
      - run: yarn build

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher

    steps:
      - checkout
      - client_build
