version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
       - "test"
       - "build"
  build:
    jobs:
      - "test"
      - "build"
