version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher

    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  buildAgain:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
  builder:
    docker:
      - image: circleci/node:12

    working_directory: ~/watcher
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build
      - checkout
      - run: npm install
      - run: npm run build


workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
       - "test"
       - "build"
       - "test"
       - "buildAgain"
       - "test"
       - "builder"
       - "test"
       - "buildAgain"
       - "test"
       - "build"
       - "test"
       - "builder"
       - "test"
       - "buildAgain"
       - "test"
       - "builder"
  build:
    jobs:
       - "test"
       - "build"
       - "test"
       - "buildAgain"
       - "test"
       - "builder"
       - "test"
       - "buildAgain"
       - "test"
       - "build"
       - "test"
       - "builder"
       - "test"
       - "buildAgain"
       - "test"
       - "builder"